### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by ghost** [CryptVenture/BitMoneyV22#1]
You did a big copyright violation against PIVX!!! Change it asap. In other case I will report it after 25th January and your repo will be offline.

Copyright (c) 2015-2018 PIVX Developers - was changed against Copyright (c) 2015-2018 BitMoney Developers

**Copyright

By contributing to this repository, you agree to license your work under the MIT license unless specified otherwise in contrib/debian/copyright or at the top of the file itself. Any work contributed where you are not the original author must contain its license header with the original author(s) and source.**

**Comment by CryptVenture** [comment]
I do not believe that we have violated any copyright notices. Files changed / adapted have been tagged with our own copyright notice in additional to the copyright chain. If PIVx feel this is in error, they are welcome to get hold of me and I will gladly make the required alterations.

**Comment by ghost** [comment]
Maybe you can't understand read my text please. This copyright snippet is in a readme from your code. I think you never saw it.

Will add you a screenshot and you can see it optically and you must not believe, because you can see it.
![image](https://user-images.githubusercontent.com/37613028/51640877-05254f80-1f65-11e9-9ed0-a5418e4a32c9.png)

You understood what you did wrong in many places of your copy??

You did a big copyright violation against PIVX!!! Change it asap. In other case I will report it after 25th January and your repo will be offline.

Copyright (c) 2015-2018 PIVX Developers - was changed against Copyright (c) 2015-2018 BitMoney Developers

**Copyright

By contributing to this repository, you agree to license your work under the MIT license unless specified otherwise in contrib/debian/copyright or at the top of the file itself. Any work contributed where you are not the original author must contain its license header with the original author(s) and source.**

**Comment by CryptVenture** [comment]
Thank you - this has now been corrected. Innocent issue in this git release which has now been resolved in the COPYING file.
