### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by ghost** [CryptVenture/BitMoneyV22#2]
Maybe you can't understand read my text please. This copyright snippet is in a readme from your code. I think you never saw it.

Will add you a screenshot and you can see it optically and you must not believe, because you can see it.

![image](https://user-images.githubusercontent.com/37613028/51640950-34d45780-1f65-11e9-8db0-e4d3d2de0722.png)

You understood what you did wrong in many places of your copy??

You did a big copyright violation against PIVX!!! Change it asap. In other case I will report it after 25th January and your repo will be offline.

Copyright (c) 2015-2018 PIVX Developers - was changed against Copyright (c) 2015-2018 BitMoney Developers

**Copyright

By contributing to this repository, you agree to license your work under the MIT license unless specified otherwise in contrib/debian/copyright or at the top of the file itself. Any work contributed where you are not the original author must contain its license header with the original author(s) and source.**

**Comment by CryptVenture** [comment]
Fixed. As per previous opened issue.
